### PR TITLE
testing pull request with compilation assist file

### PR DESCRIPTION
**Pull request by 18praveenb**
now, when in src folder in terminal, can ‘javac @args’ and ‘java
game.Main’ to compile + run directly (will generate class files in src
directory though)

### CODE REVIEW

**Comment by 4gatepylon** [comment]
What is praveen doing here?  I just got back from ~ 1 week w/ no internet get me up to speed.  (You can join if you want, I just wanna know what's up).

**Comment by 18praveenb** [comment]
Just curious. If you want a free hand for art/music/java I’d be happy to work in spare time—can you get me details of the project (goals/design/art-music style)?

**Comment by 4gatepylon** [comment]
Sure you can maybe help with Java, if we have another meeting we can plan for bigger plans.  I'll handle music, and the group can handle art together.  No ridiculous hat art >_>

**Comment by 18praveenb** [comment]
wait what emails are turned into pull requests
this is new

**Pull request merged**
